config/routes.rb
Rails.application.routes.draw do
  resources :products do
    # resources :comments, only: [:index, :new, :create]
    resources :comments, shallow: true, only: [:create, :destroy]

    member do
      post :like
      delete :unlike
      # /products/:id/buy
      get :buy
    end
  end

  # resources :comments, only: [:shoow, :edit, :update, :destroy]

  resource :users, only: [:create] do
    get "sign_up"
    get "login"
  end

  resource :sessions, only: [:create, :destroy]

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true

  belongs_to :user
  has_one_attached :cover

  has_many :user_favorites
  has_many :users, through: :user_favorites
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :name, presence: true
  validates :password, presence: true, confirmation: true

  has_many :products
  has_many :comments

  has_many :user_favorites
  has_many :favorite_products, through: :user_favorites, source: :product

  def like?(product)
    favorite_products.exists?(product.id)
  end
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :name, presence: true
  validates :party, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  helper_method :user_signed_in?, :current_user

  private
  def record_not_found
    render file: Rails.root.join("public/404.html"),
           layout: false,
           status: 404
  end

  def user_signed_in?
    session[:thankyou9527].present?
  end

  def current_user
    # memorization
    @_user_ ||= User.find_by(id: session[:thankyou9527])
  end

  def authenticate_user!
    redirect_to login_users_path, notice: "請先登入會員" if not user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product

  def create
    @comment = @product.comments.new(comment_params)

    if @comment.save
      # redirect_to product_path(@product), notice: "留言成功"
    else
      render "products/show"
    end
  end

  def destroy
  end

  private
  def find_product
    @product = Product.find(params[:product_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :like, :unlike, :buy]
  before_action :find_user_product, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.order(created_at: :desc)
  end

  def new
    if user_signed_in?
      @product = Product.new
    else
      redirect_to root_path, notice: "請先登入會員"
    end
  end

  def create
    @product = current_user.products.new(product_params)

    if @product.save
      redirect_to root_path, notice: "商品新增成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to root_path, notice: "商品更新成功"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path, notice: "商品已刪除"
  end

  def like
    if not @product.users.exists?(current_user.id)
      @product.users << current_user
      render json: {status: "added", id: @product.id}
    else
      render json: {status: "not modify", id: @product.id}
    end
  end

  def unlike
    if @product.users.exists?(current_user.id)
      @product.users.delete(current_user) 
      render json: {status: "removed", id: @product.id}
    else
      render json: {status: "not modify", id: @product.id}
    end
  end

  def buy
    # gateway = Braintree::Gateway.new(
    #   :environment => :sandbox,
    #   :merchant_id => 'your-merchant-id',
    #   :public_key => 'your-public-key',
    #   :private_key => 'your-private-key',
    # )

    # @token = gateway.client_token.generate
  end

  private

  def product_params
    params.require(:product).permit(
      :title, :price, :sku, :description, :cover
    )
  end

  def find_product
    @product = Product.find(params["id"])
  end

  def find_user_product
    @product = current_user.products.find(params["id"])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])&.authenticate(params[:password])

    if user
      session[:thankyou9527] = user.id
      redirect_to root_path, notice: "登入成功"
    else
      redirect_to login_users_path, notice: "登入失敗"
    end
  end

  def destroy
    session[:thankyou9527] = nil
    redirect_to login_users_path, notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_users_path, notice: "會員註冊成功"
    else
      render :sign_up
    end
  end

  def login
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  #先處理index
  def index
    @votes = Vote.all
  end

  def new
    @votes = Vote.new
  end

  def create
    @votes = Vote.new(vote_params)
    
    if @votes.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @votes = Vote.find(params["id"])
  end

  def destroy
    @votes = Vote.find(params["id"])
    @votes.destroy
    redirect_to root_path
  end

  private

  def vote_params
    params.require(:vote).permit(
      :name, :party, :age, :politics, :votes
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_signed_in?
    session[:thankyouhi].present?
  end

  def current_user
    User.find_by(id: session[:thankyouhi])
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<li><%= comment.content %></li>

app/views/comments/create.js.erb
var comment_area = document.querySelector(".comment_outer")
var content = "<%= j render 'comments/comment', comment: @comment %>"
comment_area.insertAdjacentHTML("afterbegin", content)
document.querySelector('#comment_form').reset()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <div class="container-fuild">
      <%= render "partials/navbar" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>首頁</h1>
<%= link_to "新增商品", new_product_path %>

app/views/pages/index.html.erb
<h1>首頁</h1>
<%= link_to "新增商品", new_product_path %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "我的商品", products_path %>
        </li>
      </ul>
      <div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= current_user.email %>
              <%= link_to "登出", sessions_path, method: "delete", class: "btn btn-dark" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "註冊", sign_up_users_path %>
            </li>
            <li class="nav-item">
              <%= link_to "登入", login_users_path %>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/products/_form.html.erb
<% if product.errors.any? %>
  <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: product) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-control">
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.number_field :sku, disabled: product.persisted? %>
  </div>

  <%= f.submit %>
<% end %>

app/views/products/buy.html.erb
<h1>我要買 <%= @product.title %>！</h1>

<div data-controller="payment" data-token="<%= @token %>"></div>

app/views/products/edit.html.erb
<h1>編輯商品</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>商品列表</h1>
<%= link_to "新增商品", new_product_path %>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.title, product_path(product) %>
      |
      <%= link_to "更新", edit_product_path(product) %>
      |
      <%= link_to "刪除", product_path(product), method: "delete", data: { confirm: "確定刪除？" } %>
    </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>新增商品</h1>



<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1>商品 <%= @product.title %></h1>

<!-- 收藏 -->
<div data-controller="favorite" data-id="<%= @product.id %>" data-favorited="<%= current_user&.like?(@product) %>">
  <button data-action="click->favorite#like" data-favorite-target="likeBtn">
    收藏
  </button>
  <button data-action="click->favorite#unlike" data-favorite-target="unlikeBtn">
    取消收藏
  </button>
</div>

<%= link_to "我要購買", buy_product_path(@product) %>

<%#= link_to "收藏", like_product_path(@product), method: "post" %> <!-- 改成上面 -->

<div>
  <%= image_tag @product.cover.variant(resize_to_limit: [200, 200]) if @product.cover.attached? %>
</div>


<%= form_with(model: @comment, url: product_comments_path(@product), local: false, id: "comment_form") do |f| %>
<%#= form_with(model: [@product, @comment]) do |f| %> <!-- 上面的漂亮寫法-->
  <%= f.text_area :content %>
  <%= f.submit "留言" %>
<% end %>

<ul class="comment_outer">
  <%#= render partial: "comments/comment", collection: @comments, as: :comment %>
  <%= render @comments %>
</ul>

app/views/shared/_navbar.html.erb
<%= link_to "商品", products_path %>

<% if user_signed_in? %>
  <%= current_user.email %>
  <%= link_to "登出", sessions_path, method: "delete" %>
<% else %>
  <%= link_to "註冊", sign_up_users_path %>
  <%= link_to "登入", login_users_path %>
<% end %>

app/views/users/login.html.erb
<h1>登入</h1>

<%= form_with(url: sessions_path, method: "post") do |form| %>
  <%= form.email_field :email %>
  <%= form.password_field :password %>
  <%= form.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>註冊</h1>

<%= form_with(model: @user) do |form| %>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "註冊" %>
<% end %>

app/views/votes/index.html.erb
<h1>投票列表</h1>

<%= link_to "新增投票", new_vote_path %>
<ul>
  <% @votes.each do |vote| %>
    <li>
      <%= link_to vote.name, vote_path(vote) %>
      ｜
      <%= link_to "刪除", vote_path(vote), method: "delete", data: {confirm: "確定刪除？"} %>
    </li>
  <% end %>
</ul>

app/views/votes/new.html.erb
<h1>新增投票</h1>

<%= form_with(model: @votes) do |f| %>
  <div class="form-control">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-control">
    <%= f.label :party %>
    <%= f.text_field :party %>
  </div>
  <div class="form-control">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div class="form-control">
    <%= f.label :politics %>
    <%= f.text_field :papoliticsrty %>
  </div>
  <div class="form-control">
    <%= f.label :votes %>
    <%= f.number_field :votes %>
  </div>
  <%= f.submit %>
<% end %>

app/views/votes/show.html.erb
<h1>投票 <%= @votes.name %></h1>

<%= link_to "返回", root_path %>